### ISSUE TITLE
Refactor Testing

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-daemon#254]
This is needed for tracking.

Read the https://github.com/TDex-network/tdex-daemon/pull/219#issuecomment-732092280 thread for reference and context.

## TODOs

- [x] Refactor domains
- [x] add unit tests for domains
- [x] add component tests
- [ ] rewrite the e2e test

**Comment by altafan** [comment]
@tiero link doesn't work.

**Comment by tiero** [comment]
> @tiero link doesn't work.

Updated
